FROM node:alpine

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm install -g @angular/cli
RUN npm install public-ip --save

RUN npm install
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]